# Generated by Django 5.2.14 on 2026-05-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('style_notes', models.TextField(blank=True, default='')),
                ('control_mode', models.CharField(choices=[('strict', 'Strict'), ('balanced', 'Balanced'), ('creative', 'Creative')], default='balanced', help_text='strict = less random, creative = more variation', max_length=20)),
                ('default_session_minutes', models.PositiveIntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='CoachTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('goal', models.CharField(default='hypertrophy', max_length=80)),
                ('level', models.CharField(default='beginner', max_length=30)),
                ('days_per_week', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=50)),
                ('split', models.JSONField(default=list, help_text="Simple days: [{'name':'Day 1','muscles':['chest','back'],'slots':4}]")),
                ('volume', models.JSONField(blank=True, default=dict, help_text="Defaults: {'sets':3,'reps':'8-12','rest_seconds':90}")),
                ('rules', models.JSONField(blank=True, default=dict, help_text="Template-local simple rules, e.g. {'avoid_same_day': [['chest','triceps']]}")),
                ('notes', models.TextField(blank=True, default='')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='programs.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('primary_muscle', models.CharField(max_length=80)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('equipment', models.CharField(blank=True, default='', max_length=80)),
                ('level', models.CharField(default='beginner', max_length=30)),
                ('movement_pattern', models.CharField(blank=True, default='', max_length=80)),
                ('risk_tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('name', 'primary_muscle')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('goal', models.CharField(default='hypertrophy', max_length=80)),
                ('level', models.CharField(default='beginner', max_length=30)),
                ('days_per_week', models.PositiveIntegerField(default=3)),
                ('session_minutes', models.PositiveIntegerField(default=60)),
                ('focus_muscles', models.JSONField(blank=True, default=list)),
                ('injuries', models.JSONField(blank=True, default=list)),
                ('available_equipment', models.JSONField(blank=True, default=list)),
                ('disliked_exercises', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='programs.coach')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=80)),
                ('signature', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.coach')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.coachtemplate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(help_text='exclude_exercises, block_risk_tags, extra_sets_for_muscles, cap_sets, prefer_equipment, note', max_length=60)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='programs.coach')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'unique_together': {('coach', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CoachExercisePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=50, help_text='0=never, 100=favorite')),
                ('allowed_levels', models.JSONField(blank=True, default=list)),
                ('blocked_for_injuries', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_preferences', to='programs.coach')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.exercise')),
            ],
            options={
                'unique_together': {('coach', 'exercise')},
            },
        ),
    ]
