# Generated by Django 5.2.14 on 2026-08-06 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_p1_rules_and_programs'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('complete', 'Complete'), ('workout', 'Workout'), ('nutrition', 'Nutrition'), ('supplement', 'Supplement')], max_length=20)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('date_range_label', models.CharField(blank=True, default='', max_length=120)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accounts.coachprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='students.student')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(default='rules_v1', max_length=40)),
                ('seed', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('output_snapshot', models.JSONField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='accounts.coachprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='students.student')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_runs', to='programming.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('training', models.JSONField(blank=True, null=True)),
                ('nutrition', models.JSONField(blank=True, null=True)),
                ('supplements', models.JSONField(blank=True, null=True)),
                ('pdf_settings', models.JSONField(blank=True, default=dict)),
                ('content_schema_version', models.PositiveIntegerField(default=1)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_versions', to='accounts.coachprofile')),
                ('copied_from_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicated_as_versions', to='programming.program')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_program_versions', to=settings.AUTH_USER_MODEL)),
                ('generation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_versions', to='programming.generationrun')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='programming.program')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='programming.programversion')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programming.programversion'),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='resulting_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programming.programversion'),
        ),
        migrations.AddIndex(
            model_name='programversion',
            index=models.Index(fields=['program', 'status'], name='programming_program_6a59f3_idx'),
        ),
        migrations.AddIndex(
            model_name='programversion',
            index=models.Index(fields=['coach', '-created_at'], name='programming_coach_i_4ef73b_idx'),
        ),
        migrations.AddConstraint(
            model_name='programversion',
            constraint=models.UniqueConstraint(fields=('program', 'version_number'), name='uniq_program_version_number'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['coach', '-updated_at'], name='programming_coach_i_63f8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['student', '-updated_at'], name='programming_student_8736b4_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['coach', 'program_type'], name='programming_coach_i_e27bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['coach', 'archived_at'], name='programming_coach_i_4be9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrun',
            index=models.Index(fields=['coach', '-created_at'], name='programming_coach_i_b3388b_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrun',
            index=models.Index(fields=['student', '-created_at'], name='programming_student_a1d66e_idx'),
        ),
    ]
