# Generated by Django 5.2.17 on 2026-10-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0001_p1_rules_and_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='programversion',
            name='delivery_source',
            field=models.CharField(choices=[('generated', 'Generated by Athlore'), ('uploaded_pdf', 'Coach PDF upload')], default='generated', max_length=20),
        ),
    ]
