"""Version-controlled Arman demo fixture payloads (idempotent seed source)."""

from __future__ import annotations

ARMAN_RULES = {
    "templates": [
        {
            "name": "۴ روزه حجم متوسط",
            "goal": "هایپرتروفی با تمرکز upper body و اولویت عضلات",
            "main_goal": "hypertrophy",
            "level": "intermediate",
            "days_per_week": 4,
            "intensity": "متوسط تا سنگین",
            "volume": "زیاد",
            "rest_time": "کوتاه تا متوسط",
            "split": ["سینه و پشت بازو", "زیربغل و جلو بازو", "پا", "سرشانه و شکم"],
            "muscle_priority_order": ["سینه", "زیربغل", "سرشانه"],
            "special_rules": [
                "compound اول جلسه",
                "accessory و isolation بعد از حرکات اصلی",
                "شکم و corrective آخر جلسه",
                "عضله ضعیف حجم کنترل‌شده بیشتر؛ در صورت نیاز یک حرکت اضافه",
                "عضله قوی حجم نگهدارنده",
                "سوپرست محدود و واقعی",
            ],
            "is_active": True,
            "sort_order": 0,
        },
        {
            "name": "فول بادی مبتدی ۳ روزه",
            "goal": "عضله‌سازی عمومی و یادگیری تکنیک",
            "main_goal": "general_muscle_gain",
            "level": "beginner",
            "days_per_week": 3,
            "intensity": "سبک تا متوسط",
            "volume": "متوسط",
            "rest_time": "متوسط",
            "split": [
                "پا و سینه و شکم",
                "زیربغل و سرشانه و کاردیو سبک",
                "فول بادی سبک و اصلاحی",
            ],
            "muscle_priority_order": ["سینه", "زیربغل", "پا"],
            "special_rules": [
                "حرکات اصلی اول جلسه",
                "از حرکات پیچیده زیاد اجتناب شود",
                "اولویت اجرای صحیح فرم",
                "تمرین تا ناتوانی انجام نشود",
            ],
            "is_active": True,
            "sort_order": 1,
        },
    ],
    "levels": [
        {
            "id": "beginner",
            "intensity": "سبک تا متوسط",
            "volume": "کم تا متوسط؛ ۲ تا ۳ ست",
            "allowed_techniques": ["ست ساده", "ریتم کنترل شده", "دامنه کامل"],
            "forbidden_exercises": [
                "ناتوانی",
                "دراپ ست پیشرفته",
                "ددلیفت سنگین",
                "اسکوات آزاد سنگین",
                "حرکات انفجاری",
            ],
            "required_exercises": ["دستگاه", "حرکات پایه", "فرم صحیح"],
            "coach_notes": "مبتدی تا failure نرود؛ ترجیح دستگاه و دامنه کامل.",
        },
        {
            "id": "intermediate",
            "intensity": "متوسط تا بالاتر",
            "volume": "حجم بیشتر نسبت به مبتدی؛ ۳ تا ۴ ست",
            "allowed_techniques": ["سوپرست محدود", "هرم سبک", "رنج تکرار", "partial reps کنترل‌شده"],
            "forbidden_exercises": ["حجم بی‌هدف روی آسیب"],
            "required_exercises": ["compound", "accessory", "وزنه آزاد بیشتر"],
            "coach_notes": "هایپرتروفی کلاسیک؛ شدت و حجم بالاتر از مبتدی.",
        },
        {
            "id": "advanced",
            "intensity": "متوسط رو به سنگین",
            "volume": "۴ تا ۵ ست اولویت‌ها",
            "allowed_techniques": ["سوپرست", "دراپ ست", "رست‌پاز محدود", "هرم"],
            "forbidden_exercises": ["تکنیک شدید روی آسیب"],
            "required_exercises": ["چندمفصلی"],
            "coach_notes": "تکنیک‌های شدت فقط با فرم صحیح و داده مربی.",
        },
    ],
    "injuries": [
        {
            "name": "گردن درد",
            "forbidden_exercises": [
                "پرس سرشانه سنگین",
                "شراگ سنگین",
                "پرس پشت گردن",
                "پرس سرشانه هالتر",
                "heavy_shoulder_press",
                "heavy_shrug",
            ],
            "alternatives": [
                "نشر جانب دمبل",
                "پرس سرشانه دستگاه",
                "فیس پول",
                "نشر جانب دستگاه",
                "حرکت کابل سبک سرشانه",
            ],
            "notes": "injury بر preference/history اولویت دارد؛ overhead سنگین حذف شود.",
            "is_active": True,
            "sort_order": 0,
        },
        {
            "name": "کمر درد",
            "forbidden_exercises": [
                "ددلیفت سنگین",
                "روئینگ هالتر خمیده سنگین",
                "اسکوات سنگین",
                "خیر رومانیایی سنگین",
            ],
            "alternatives": [
                "لت سیم کش",
                "روئینگ دستگاه",
                "هیپ تراست سبک",
                "پرس پا",
                "ددلیفت رومانیایی سبک",
            ],
            "notes": "فشار محوری کنترل‌نشده حذف شود.",
            "is_active": True,
            "sort_order": 1,
        },
        {
            "name": "زانو درد",
            "forbidden_exercises": [
                "اسکوات سنگین",
                "لانج سنگین",
                "اسکوات پرشی",
                "لانج پرشی",
            ],
            "alternatives": [
                "پرس پا سبک",
                "جلوپا دستگاه کنترل‌شده",
                "پل باسن",
                "حرکات اصلاحی",
            ],
            "notes": "پرش و دامنه دردناک حذف شود.",
            "is_active": True,
            "sort_order": 2,
        },
    ],
    "muscle_priorities": [
        {
            "muscle": "سینه",
            "extra_exercises": 1,
            "extra_sets": 1,
            "order_change": "اول جلسه؛ بالاسینه اولویت",
            "notes": "ضعیف: زودتر در جلسه + یک حرکت اضافه در صورت مناسب بودن.",
            "sort_order": 0,
        },
        {
            "muscle": "زیربغل",
            "extra_exercises": 1,
            "extra_sets": 1,
            "order_change": "افزایش حجم کششی/کششی-کششی",
            "notes": "ضعیف: حجم پشت/لت بیشتر با کار کششی مناسب.",
            "sort_order": 1,
        },
        {
            "muscle": "پا",
            "extra_exercises": 0,
            "extra_sets": 1,
            "order_change": "ترجیح روز پای کامل جدا",
            "notes": "ضعیف: روز پای کامل جداگانه ترجیح داده شود.",
            "sort_order": 2,
        },
        {
            "muscle": "سرشانه",
            "extra_exercises": 0,
            "extra_sets": 1,
            "order_change": "lateral و rear-delt پوشش داده شود",
            "notes": "",
            "sort_order": 3,
        },
        {
            "muscle": "پشت بازو",
            "extra_exercises": 0,
            "extra_sets": 1,
            "order_change": "بعد از سینه",
            "notes": "",
            "sort_order": 4,
        },
    ],
    "exercise_bank": [
        {
            "group": "سینه",
            "favorite_exercises": [
                "پرس سینه هالتر",
                "پرس بالا سینه دمبل",
                "پرس سینه دستگاه",
                "کراس اور",
            ],
            "beginner_friendly": ["پرس سینه دستگاه", "شنا سوئدی", "پرس بالا سینه دمبل سبک"],
            "professional_friendly": ["پرس سینه هالتر", "دیپ وزنه‌دار"],
            "forbidden_exercises": [],
            "sort_order": 0,
        },
        {
            "group": "زیربغل",
            "favorite_exercises": ["لت سیم کش", "روئینگ نشسته", "روئینگ تکیه‌گاهی"],
            "beginner_friendly": ["لت سیم کش", "روئینگ دستگاه"],
            "professional_friendly": ["بارفیکس", "روئینگ سنگین"],
            "forbidden_exercises": ["روئینگ هالتر خمیده خیلی سنگین برای مبتدی", "شراگ سنگین"],
            "sort_order": 1,
        },
        {
            "group": "پا",
            "favorite_exercises": ["پرس پا", "اسکوات", "ددلیفت رومانیایی", "پشت پا دستگاه"],
            "beginner_friendly": ["پرس پا", "گابلت اسکوات"],
            "professional_friendly": ["اسکوات پشت", "ددلیفت رومانیایی"],
            "forbidden_exercises": ["اسکوات سنگین برای مبتدی", "اسکوات پرشی"],
            "sort_order": 2,
        },
        {
            "group": "سرشانه",
            "favorite_exercises": ["پرس سرشانه دستگاه", "نشر جانب دمبل", "فیس پول"],
            "beginner_friendly": ["پرس سرشانه دستگاه", "نشر جانب دمبل"],
            "professional_friendly": ["نشر جانب دمبل", "فیس پول"],
            "forbidden_exercises": ["پرس پشت گردن", "پرس سرشانه سنگین"],
            "sort_order": 3,
        },
        {
            "group": "جلو بازو",
            "favorite_exercises": ["جلو بازو دمبل", "جلو بازو هالتر", "چکش دمبل"],
            "beginner_friendly": ["جلو بازو دمبل"],
            "professional_friendly": ["جلو بازو هالتر", "چکش دمبل"],
            "forbidden_exercises": [],
            "sort_order": 4,
        },
        {
            "group": "پشت بازو",
            "favorite_exercises": ["پشت بازو سیم‌کش", "دیپ نیمکت", "پشت بازو دمبل"],
            "beginner_friendly": ["پشت بازو سیم‌کش"],
            "professional_friendly": ["دیپ نیمکت", "پشت بازو دمبل"],
            "forbidden_exercises": [],
            "sort_order": 5,
        },
        {
            "group": "شکم",
            "favorite_exercises": ["کرانچ", "پلانک", "زیرشکم پا آویزان"],
            "beginner_friendly": ["کرانچ", "پلانک"],
            "professional_friendly": ["زیرشکم پا آویزان"],
            "forbidden_exercises": [],
            "sort_order": 6,
        },
    ],
    "general_rules": {
        "extra_notes": (
            "هایپرتروفی کلاسیک؛ compound اول، accessory بعد، شکم/corrective آخر؛ "
            "injury همیشه بر preference و history اولویت دارد؛ "
            "برای دو ورزشکار مشابه تنوع کنترل‌شده در حرکت/ترتیب/ست."
        ),
        "items": [
            {
                "title": "Compound اول جلسه",
                "description": "حرکات چندمفصلی اول برنامه باشند.",
                "category": "ترتیب تمرین",
                "importance": "high",
                "is_active": True,
                "order": 1,
            },
            {
                "title": "Accessory بعد از اصلی",
                "description": "isolation و accessory بعد از compound.",
                "category": "ترتیب تمرین",
                "importance": "high",
                "is_active": True,
                "order": 2,
            },
            {
                "title": "شکم و corrective آخر",
                "description": "core و اصلاحی در انتهای جلسه.",
                "category": "ترتیب تمرین",
                "importance": "medium",
                "is_active": True,
                "order": 3,
            },
            {
                "title": "مبتدی بدون failure",
                "description": "شاگرد مبتدی تا ناتوانی تمرین نکند.",
                "category": "ایمنی",
                "importance": "high",
                "is_active": True,
                "order": 4,
            },
            {
                "title": "حجم عضله ضعیف/قوی",
                "description": "ضعیف حجم بیشتر کنترل‌شده؛ قوی نگهدارنده.",
                "category": "اولویت عضلات",
                "importance": "high",
                "is_active": True,
                "order": 5,
            },
            {
                "title": "سوپرست محدود واقعی",
                "description": "فقط جفت‌های واقعی؛ حرکت منفرد سوپرست نشود.",
                "category": "تکنیک",
                "importance": "medium",
                "is_active": True,
                "order": 6,
            },
            {
                "title": "اولویت injury",
                "description": "حرکات ممنوع آسیب از preference و history مهم‌ترند.",
                "category": "ایمنی",
                "importance": "high",
                "is_active": True,
                "order": 7,
            },
            {
                "title": "تنوع کنترل‌شده",
                "description": "برای ورزشکاران مشابه، تنوع جزئی در حرکت، ترتیب و تعداد ست.",
                "category": "تنوع",
                "importance": "medium",
                "is_active": True,
                "order": 8,
            },
            {
                "title": "اجرای صحیح مهم است",
                "description": "فرم و دامنه صحیح بر شدت بی‌کیفیت اولویت دارد.",
                "category": "فرم",
                "importance": "high",
                "is_active": True,
                "order": 9,
            },
        ],
    },
}

# Extra catalog coverage so Generator never depends only on generic fallbacks.
EXTRA_STANDARD_EXERCISES: list[dict] = [
    {
        "name": "پلانک",
        "primary_muscle": "شکم",
        "equipment": "وزن بدن",
        "movement_pattern": "core_stability",
        "laterality": "bilateral",
    },
    {
        "name": "کرانچ",
        "primary_muscle": "شکم",
        "equipment": "وزن بدن",
        "movement_pattern": "core_flexion",
        "laterality": "bilateral",
    },
    {
        "name": "زیرشکم پا آویزان",
        "primary_muscle": "شکم",
        "equipment": "وزن بدن",
        "movement_pattern": "core_flexion",
        "laterality": "bilateral",
    },
    {
        "name": "برد داگ",
        "primary_muscle": "شکم",
        "secondary_muscles": ["کمر"],
        "equipment": "وزن بدن",
        "movement_pattern": "corrective",
        "laterality": "unilateral",
    },
    {
        "name": "فیس پول",
        "primary_muscle": "سرشانه",
        "equipment": "کابل",
        "movement_pattern": "pull_horizontal",
        "laterality": "bilateral",
    },
    {
        "name": "ساق ایستاده",
        "primary_muscle": "پا",
        "equipment": "دستگاه",
        "movement_pattern": "isolation",
        "laterality": "bilateral",
    },
    {
        "name": "پشت پا دستگاه",
        "primary_muscle": "پا",
        "equipment": "دستگاه",
        "movement_pattern": "hinge",
        "laterality": "bilateral",
    },
    {
        "name": "چکش دمبل",
        "primary_muscle": "جلو بازو",
        "equipment": "دمبل",
        "movement_pattern": "isolation",
        "laterality": "unilateral",
    },
    {
        "name": "پرس سرشانه سنگین",
        "primary_muscle": "سرشانه",
        "equipment": "هالتر",
        "movement_pattern": "push_vertical",
        "laterality": "bilateral",
        "prohibited": True,
    },
    {
        "name": "شراگ سنگین",
        "primary_muscle": "سرشانه",
        "equipment": "هالتر",
        "movement_pattern": "shrug",
        "laterality": "bilateral",
        "prohibited": True,
    },
    {
        "name": "پرس پشت گردن",
        "primary_muscle": "سرشانه",
        "equipment": "هالتر",
        "movement_pattern": "push_vertical",
        "laterality": "bilateral",
        "prohibited": True,
    },
]

DEMO_SUPPLEMENT_ITEMS = [
    {
        "name": "Whey",
        "quantity_text": "1 scoop",
        "timing": "صبح ناشتا",
        "instructions": "demo",
        "warnings": "",
    },
    {
        "name": "Whey",
        "quantity_text": "1 scoop",
        "timing": "بعد تمرین",
        "instructions": "demo",
        "warnings": "",
    },
    {
        "name": "Creatine",
        "quantity_text": "1 scoop",
        "timing": "بعد تمرین",
        "instructions": "demo",
        "warnings": "",
    },
    {
        "name": "Amino",
        "quantity_text": "1 scoop",
        "timing": "حین تمرین",
        "instructions": "demo",
        "warnings": "",
    },
]
