# Generated by Django 5.2.14 on 2026-08-06 15:10

import delivery.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_p1_rules_and_programs'),
        ('programming', '0001_p1_rules_and_programs'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, max_length=512, null=True, upload_to=delivery.models.pdf_artifact_upload_to)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('render_engine_version', models.CharField(blank=True, default='', max_length=64)),
                ('template_version', models.CharField(blank=True, default='', max_length=32)),
                ('program_type', models.CharField(blank=True, default='', max_length=20)),
                ('version_label', models.CharField(blank=True, default='', max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_summary', models.CharField(blank=True, default='', max_length=300)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_artifacts', to='accounts.coachprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pdf_artifacts', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_artifacts', to='programming.program')),
                ('program_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_artifacts', to='programming.programversion')),
                ('regenerated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerations', to='delivery.pdfartifact')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_artifacts', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PdfShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='delivery.pdfartifact')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_share_links', to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pdfartifact',
            index=models.Index(fields=['coach', '-created_at'], name='delivery_pd_coach_i_07aa6f_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfartifact',
            index=models.Index(fields=['student', '-created_at'], name='delivery_pd_student_236da8_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfartifact',
            index=models.Index(fields=['program', '-created_at'], name='delivery_pd_program_3a53fa_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfartifact',
            index=models.Index(fields=['program_version'], name='delivery_pd_program_ac6acb_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfartifact',
            index=models.Index(fields=['coach', 'status'], name='delivery_pd_coach_i_3e772d_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfartifact',
            index=models.Index(fields=['coach', 'deleted_at'], name='delivery_pd_coach_i_ab7126_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfsharelink',
            index=models.Index(fields=['artifact', '-created_at'], name='delivery_pd_artifac_ce2f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfsharelink',
            index=models.Index(fields=['coach', '-created_at'], name='delivery_pd_coach_i_a806c3_idx'),
        ),
    ]
