# Generated by Django 5.2.17 on 2026-10-10 12:16

import delivery.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_coach_calendar'),
        ('delivery', '0001_p3_pdf_artifacts'),
        ('programming', '0002_programversion_delivery_source'),
        ('students', '0015_stagedvisitphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfartifact',
            name='source',
            field=models.CharField(choices=[('generated', 'Generated'), ('uploaded', 'Uploaded by coach')], default='generated', max_length=16),
        ),
        migrations.CreateModel(
            name='StagedProgramPdf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=512, upload_to=delivery.models.staged_program_pdf_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_program_pdfs', to='accounts.coachprofile')),
                ('program_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_pdf_upload', to='programming.programversion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_program_pdfs', to='students.student')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_program_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coach', 'expires_at'], name='delivery_st_coach_i_fd250e_idx')],
            },
        ),
    ]
