# Generated by Django 5.2.17 on 2026-10-10 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_coach_calendar"),
        ("delivery", "0002_pdfartifact_source_stagedprogrampdf"),
        ("programming", "0002_programversion_delivery_source"),
        ("students", "0015_stagedvisitphoto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfartifact",
            name="section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("workout", "Workout"),
                    ("nutrition", "Nutrition"),
                    ("supplement", "Supplements"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stagedprogrampdf",
            name="section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("workout", "Workout"),
                    ("nutrition", "Nutrition"),
                    ("supplement", "Supplements"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stagedprogrampdf",
            name="program_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staged_pdf_uploads",
                to="programming.programversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedprogrampdf",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("program_version__isnull", False), models.Q(("section", ""), _negated=True)
                ),
                fields=("program_version", "section"),
                name="uniq_staged_pdf_version_section",
            ),
        ),
    ]
