# Generated by Django 5.2.14 on 2026-08-06 13:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('50'))])),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('20'))])),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('coach_notes', models.TextField(blank=True, default='')),
                ('goals', models.JSONField(blank=True, default=dict)),
                ('injuries', models.JSONField(blank=True, default=dict)),
                ('equipment', models.JSONField(blank=True, default=dict)),
                ('lifestyle', models.JSONField(blank=True, default=dict)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('training_background', models.JSONField(blank=True, default=dict)),
                ('training_conditions', models.JSONField(blank=True, default=dict)),
                ('summary_current_program_title', models.CharField(blank=True, default='', max_length=200)),
                ('summary_last_visit_date', models.DateField(blank=True, null=True)),
                ('summary_medical_note', models.CharField(blank=True, default='', max_length=300)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('current_weight_kg', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('20'))])),
                ('previous_weight_kg', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('20'))])),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('arm_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('thigh_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hip_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('adherence_overall', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('adherence_training', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('adherence_nutrition', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('adherence_supplements', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('daily_energy_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('good', 'Good'), ('high', 'High')], max_length=16)),
                ('sleep_quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('good', 'Good'), ('high', 'High')], max_length=16)),
                ('stress_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('good', 'Good'), ('high', 'High')], max_length=16)),
                ('body_feeling', models.TextField(blank=True, default='')),
                ('student_feedback', models.TextField(blank=True, default='')),
                ('coach_assessment', models.TextField(blank=True, default='')),
                ('coach_notes', models.TextField(blank=True, default='')),
                ('has_new_injury', models.BooleanField(default=False)),
                ('new_injury_notes', models.TextField(blank=True, default='')),
                ('next_cycle_goal', models.TextField(blank=True, default='')),
                ('training_condition_changes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounts.coachprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='students.student')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['coach', 'status'], name='students_st_coach_i_27aae2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['coach', 'full_name'], name='students_st_coach_i_d155f9_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['student', '-visit_date'], name='students_vi_student_bb9621_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['coach', '-visit_date'], name='students_vi_coach_i_62262b_idx'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('student', 'visit_date'), name='uniq_student_visit_date'),
        ),
    ]
