# Generated by Django 5.2.17 on 2026-08-09 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_assessment_and_style_profile'),
        ('students', '0003_nutrition_safety_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAssessmentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('sections', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_templates', to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_key', models.CharField(blank=True, default='', max_length=80)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('template_snapshot', models.JSONField(blank=True, default=dict)),
                ('assessment_date', models.DateField()),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('coach_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='accounts.coachprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.student')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='students.coachassessmenttemplate')),
            ],
            options={
                'ordering': ['-assessment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coachassessmenttemplate',
            index=models.Index(fields=['coach', 'is_active'], name='students_co_coach_i_dd04a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachassessmenttemplate',
            constraint=models.UniqueConstraint(fields=('coach', 'key'), name='uniq_coach_assessment_template_key'),
        ),
        migrations.AddIndex(
            model_name='studentassessment',
            index=models.Index(fields=['student', '-assessment_date'], name='students_st_student_ad05bb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassessment',
            index=models.Index(fields=['coach', '-assessment_date'], name='students_st_coach_i_af1c09_idx'),
        ),
    ]
