# Generated by Django 5.2.17 on 2026-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_visit_lifecycle_and_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='account_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='activation_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='activation_code_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='activation_code_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portal_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
