# Generated by Django 5.2.17 on 2026-08-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_portal_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waiting_for_student', 'Waiting for student'), ('student_submitted', 'Student submitted'), ('coach_review', 'Coach review'), ('finalized', 'Finalized')], default='draft', max_length=32),
        ),
    ]
