# Generated by Django 5.2.17 on 2026-08-21 18:33

import django.core.validators
import django.db.models.deletion
import students.body_check_models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_assessment_and_style_profile'),
        ('students', '0009_student_portal_initial_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyCheckCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=16)),
                ('starting_weight_kg', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('20')), django.core.validators.MaxValueValidator(Decimal('400'))])),
                ('goal_weight_kg', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('20')), django.core.validators.MaxValueValidator(Decimal('400'))])),
                ('daily_targets_kg', models.JSONField(blank=True, default=list)),
                ('meal_detail_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_check_cycles', to='accounts.coachprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_check_cycles', to='students.student')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BodyCheckDailyEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_date', models.DateField()),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('20')), django.core.validators.MaxValueValidator(Decimal('400'))])),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('20')), django.core.validators.MaxValueValidator(Decimal('400'))])),
                ('sleep_start_time', models.TimeField(blank=True, null=True)),
                ('wake_time', models.TimeField(blank=True, null=True)),
                ('sleep_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_quality_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('nutrition_adherence_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('meal_1', models.TextField(blank=True, default='')),
                ('meal_2', models.TextField(blank=True, default='')),
                ('meal_3', models.TextField(blank=True, default='')),
                ('meal_4', models.TextField(blank=True, default='')),
                ('meal_5', models.TextField(blank=True, default='')),
                ('meal_6', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='students.bodycheckcycle')),
            ],
            options={
                'ordering': ['local_date'],
            },
        ),
        migrations.CreateModel(
            name='BodyCheckProgressPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('file', models.FileField(max_length=512, upload_to=students.body_check_models.body_check_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to='students.bodycheckcycle')),
            ],
            options={
                'ordering': ['week_number', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bodycheckcycle',
            index=models.Index(fields=['coach', 'student', 'status'], name='students_bo_coach_i_30c416_idx'),
        ),
        migrations.AddIndex(
            model_name='bodycheckcycle',
            index=models.Index(fields=['student', 'status'], name='students_bo_student_cb7502_idx'),
        ),
        migrations.AddIndex(
            model_name='bodycheckdailyentry',
            index=models.Index(fields=['cycle', 'local_date'], name='students_bo_cycle_i_ddc4f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='bodycheckdailyentry',
            constraint=models.UniqueConstraint(fields=('cycle', 'local_date'), name='uniq_body_check_entry_per_cycle_date'),
        ),
        migrations.AddIndex(
            model_name='bodycheckprogressphoto',
            index=models.Index(fields=['cycle', 'week_number'], name='students_bo_cycle_i_370620_idx'),
        ),
    ]
