# Generated by Django 5.2.17 on 2026-10-08 16:45

import django.db.models.deletion
import students.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_bodycheckcycle_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploader_role', models.CharField(choices=[('coach', 'Coach'), ('student', 'Student')], max_length=16)),
                ('file', models.FileField(max_length=512, upload_to=students.models.visit_photo_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_photos_uploaded', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='students.visit')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
                'indexes': [models.Index(fields=['visit', 'uploaded_at'], name='students_vi_visit_i_056a8a_idx')],
            },
        ),
    ]
