# Generated by Django 5.2.14 on 2026-08-06 14:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('primary_muscle', models.CharField(max_length=80)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('equipment', models.CharField(blank=True, default='', max_length=80)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All')], default='beginner', max_length=30)),
                ('movement_pattern', models.CharField(blank=True, default='', max_length=80)),
                ('risk_tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['primary_muscle', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoachExercisePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_preferred', models.BooleanField(default=False)),
                ('is_prohibited', models.BooleanField(default=False)),
                ('suitable_levels', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_preferences', to='accounts.coachprofile')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='accounts.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseBankGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=80)),
                ('favorite_exercises', models.JSONField(blank=True, default=list)),
                ('beginner_friendly', models.JSONField(blank=True, default=list)),
                ('professional_friendly', models.JSONField(blank=True, default=list)),
                ('forbidden_exercises', models.JSONField(blank=True, default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_bank_groups', to='accounts.coachprofile')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_bank_groups', to='accounts.coachruleset')),
            ],
            options={
                'ordering': ['sort_order', 'group_name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('importance', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_rules', to='accounts.coachprofile')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_rules', to='accounts.coachruleset')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InjuryRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('forbidden_exercises', models.JSONField(blank=True, default=list)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_rules', to='accounts.coachprofile')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_rules', to='accounts.coachruleset')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LevelRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_key', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('intensity', models.TextField(blank=True, default='')),
                ('volume', models.TextField(blank=True, default='')),
                ('allowed_techniques', models.JSONField(blank=True, default=list)),
                ('forbidden_exercises', models.JSONField(blank=True, default=list)),
                ('required_exercises', models.JSONField(blank=True, default=list)),
                ('coach_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_rules', to='accounts.coachprofile')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_rules', to='accounts.coachruleset')),
            ],
            options={
                'ordering': ['level_key'],
            },
        ),
        migrations.CreateModel(
            name='MusclePriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('muscle', models.CharField(max_length=80)),
                ('extra_exercises', models.PositiveIntegerField(default=0)),
                ('extra_sets', models.PositiveIntegerField(default=0)),
                ('order_change', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_priorities', to='accounts.coachprofile')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_priorities', to='accounts.coachruleset')),
            ],
            options={
                'ordering': ['sort_order', 'muscle'],
            },
        ),
        migrations.CreateModel(
            name='ProgramTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('goal', models.CharField(blank=True, default='', max_length=200)),
                ('main_goal', models.CharField(blank=True, default='', max_length=120)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('days_per_week', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('intensity', models.CharField(blank=True, default='', max_length=80)),
                ('volume', models.CharField(blank=True, default='', max_length=80)),
                ('rest_time', models.CharField(blank=True, default='', max_length=80)),
                ('split', models.JSONField(blank=True, default=list)),
                ('muscle_priority_order', models.JSONField(blank=True, default=list)),
                ('special_rules', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_templates', to='accounts.coachprofile')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='accounts.coachruleset')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['coach', 'primary_muscle'], name='accounts_ex_coach_i_2b122c_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['coach', 'is_archived'], name='accounts_ex_coach_i_9db71f_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['coach', 'name'], name='accounts_ex_coach_i_29e8c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('coach', 'name', 'primary_muscle'), name='uniq_coach_exercise_name_muscle'),
        ),
        migrations.AddConstraint(
            model_name='coachexercisepreference',
            constraint=models.UniqueConstraint(fields=('coach', 'exercise'), name='uniq_coach_exercise_preference'),
        ),
        migrations.AddConstraint(
            model_name='levelrule',
            constraint=models.UniqueConstraint(fields=('rule_set', 'level_key'), name='uniq_level_rule_per_set'),
        ),
        migrations.AddIndex(
            model_name='programtemplate',
            index=models.Index(fields=['coach', 'is_active'], name='accounts_pr_coach_i_728fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='programtemplate',
            index=models.Index(fields=['coach', 'is_archived'], name='accounts_pr_coach_i_d18333_idx'),
        ),
    ]
