# Generated by Django 5.2.14 on 2026-08-06 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phone_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='laterality',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('unilateral', 'Unilateral'), ('bilateral', 'Bilateral')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='exercise',
            name='source_document',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='CoachNutritionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('purpose', models.CharField(blank=True, default='', max_length=255)),
                ('day_type', models.CharField(blank=True, choices=[('', 'Not specified'), ('training', 'Training day'), ('rest', 'Rest day')], default='', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('needs_coach_review', models.BooleanField(default=True)),
                ('source_document', models.CharField(blank=True, default='', max_length=255)),
                ('source_version', models.CharField(blank=True, default='', max_length=60)),
                ('is_eligible_for_auto_select', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_templates', to='accounts.coachprofile')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_templates', to='accounts.coachruleset')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoachSupplementTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('needs_coach_review', models.BooleanField(default=True)),
                ('source_documents', models.JSONField(blank=True, default=list)),
                ('is_eligible_for_auto_select', models.BooleanField(default=False)),
                ('medical_disclaimer', models.TextField(blank=True, default='این برنامه مکمل صرفاً یک پیشنهاد مرجع است و جای مشاوره پزشک یا متخصص تغذیه را نمی\u200cگیرد. پیش از مصرف هرگونه مکمل، به\u200cویژه در صورت وجود بیماری زمینه\u200cای، بارداری، شیردهی یا مصرف داروی دیگر، حتماً با پزشک یا متخصص تغذیه مشورت کنید.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_templates', to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_aliases', to='accounts.coachprofile')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='accounts.exercise')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseHistoricalUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_program_key', models.CharField(max_length=120)),
                ('source_date', models.CharField(blank=True, default='', max_length=32)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('raw_prescription', models.TextField()),
                ('day_label', models.CharField(blank=True, default='', max_length=160)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_historical_usages', to='accounts.coachprofile')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_usages', to='accounts.exercise')),
            ],
            options={
                'ordering': ['source_date', 'day_label'],
            },
        ),
        migrations.CreateModel(
            name='NutritionMealSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_key', models.CharField(choices=[('breakfast', 'Breakfast'), ('snack_1', 'Snack 1'), ('lunch', 'Lunch'), ('lunch_side', 'Lunch side'), ('snack_2', 'Snack 2'), ('dinner', 'Dinner'), ('dinner_side', 'Dinner side'), ('snack_3', 'Snack 3')], max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='accounts.coachnutritiontemplate')),
            ],
            options={
                'ordering': ['sort_order', 'slot_key'],
            },
        ),
        migrations.CreateModel(
            name='NutritionMealOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_index', models.PositiveIntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='accounts.nutritionmealslot')),
            ],
            options={
                'ordering': ['sort_order', 'option_index'],
            },
        ),
        migrations.CreateModel(
            name='NutritionOptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('food_name', models.CharField(max_length=200)),
                ('quantity_text', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, default='', max_length=60)),
                ('preparation', models.CharField(blank=True, default='', max_length=255)),
                ('substitution_group', models.CharField(blank=True, default='', max_length=120)),
                ('needs_review', models.BooleanField(default=False)),
                ('reviewed_quantity', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.nutritionmealoption')),
            ],
            options={
                'ordering': ['sort_order', 'food_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplementTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('quantity_text', models.CharField(max_length=200)),
                ('timing', models.CharField(blank=True, default='', max_length=120)),
                ('frequency', models.CharField(blank=True, default='', max_length=120)),
                ('day_applicability', models.CharField(blank=True, default='', max_length=20)),
                ('instructions', models.TextField(blank=True, default='')),
                ('warnings', models.TextField(blank=True, default='')),
                ('needs_review', models.BooleanField(default=True)),
                ('normalized_amount', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.coachsupplementtemplate')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='coachnutritiontemplate',
            constraint=models.UniqueConstraint(fields=('coach', 'name'), name='uniq_coach_nutrition_template_name'),
        ),
        migrations.AddConstraint(
            model_name='coachsupplementtemplate',
            constraint=models.UniqueConstraint(fields=('coach', 'name'), name='uniq_coach_supplement_template_name'),
        ),
        migrations.AddIndex(
            model_name='exercisealias',
            index=models.Index(fields=['coach', 'alias'], name='accounts_ex_coach_i_f7ee80_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisealias',
            constraint=models.UniqueConstraint(fields=('coach', 'alias'), name='uniq_coach_exercise_alias'),
        ),
        migrations.AddConstraint(
            model_name='exercisealias',
            constraint=models.UniqueConstraint(fields=('coach', 'exercise', 'alias'), name='uniq_coach_exercise_alias_per_exercise'),
        ),
        migrations.AddIndex(
            model_name='exercisehistoricalusage',
            index=models.Index(fields=['coach', 'exercise'], name='accounts_ex_coach_i_ac6bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisehistoricalusage',
            index=models.Index(fields=['coach', 'source_program_key'], name='accounts_ex_coach_i_307f98_idx'),
        ),
        migrations.AddConstraint(
            model_name='nutritionmealslot',
            constraint=models.UniqueConstraint(fields=('template', 'slot_key'), name='uniq_template_meal_slot'),
        ),
        migrations.AddConstraint(
            model_name='nutritionmealoption',
            constraint=models.UniqueConstraint(fields=('slot', 'option_index'), name='uniq_slot_option_index'),
        ),
    ]
