# Generated by Django 5.2.17 on 2026-08-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reference_bank_nutrition_supplements'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachruleset',
            name='style_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
