# Generated by Django 5.2.17 on 2026-09-17

import hashlib

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _legacy_key(prefix, value):
    digest = hashlib.sha1(str(value).encode("utf-8")).hexdigest()[:12]
    return f"legacy-{prefix}-{digest}"


def seed_taxonomy_and_migrate_legacy(apps, schema_editor):
    MuscleTaxonomy = apps.get_model("accounts", "MuscleTaxonomy")
    MuscleRegion = apps.get_model("accounts", "MuscleRegion")
    EquipmentTaxonomy = apps.get_model("accounts", "EquipmentTaxonomy")
    Exercise = apps.get_model("accounts", "Exercise")
    ExerciseMuscleTarget = apps.get_model("accounts", "ExerciseMuscleTarget")
    ExerciseSuitableLevel = apps.get_model("accounts", "ExerciseSuitableLevel")
    ExerciseEquipment = apps.get_model("accounts", "ExerciseEquipment")
    Preference = apps.get_model("accounts", "CoachExercisePreference")
    TrainingTechnique = apps.get_model("accounts", "TrainingTechnique")

    muscles = [
        ("chest", "سینه", "Chest"),
        ("back", "زیربغل", "Back"),
        ("shoulders", "سرشانه", "Shoulders"),
        ("quadriceps", "چهارسر ران", "Quadriceps"),
        ("hamstrings", "همسترینگ", "Hamstrings"),
        ("glutes", "باسن", "Glutes"),
        ("biceps", "جلو بازو", "Biceps"),
        ("triceps", "پشت بازو", "Triceps"),
        ("calves", "ساق", "Calves"),
        ("core", "میان تنه", "Core"),
    ]
    muscle_rows = {}
    for sort_order, (key, name, name_en) in enumerate(muscles):
        muscle_rows[key], _ = MuscleTaxonomy.objects.get_or_create(
            key=key,
            defaults={"name": name, "name_en": name_en, "sort_order": sort_order},
        )

    regions = {
        "chest": [
            ("upper_chest", "بالاسینه", "Upper chest"),
            ("mid_chest", "بخش میانی سینه", "Mid chest"),
            ("lower_chest", "پایین سینه", "Lower chest"),
        ],
        "back": [("upper_back", "بخش بالایی پشت", "Upper back"), ("lats", "لت", "Lats")],
        "shoulders": [
            ("front_delt", "دلتوئید قدامی", "Front delt"),
            ("side_delt", "دلتوئید میانی", "Side delt"),
            ("rear_delt", "دلتوئید خلفی", "Rear delt"),
        ],
        "quadriceps": [("vastus", "بخش اصلی چهارسر", "Vastus")],
        "hamstrings": [("posterior_chain", "زنجیره خلفی", "Posterior chain")],
        "glutes": [("glute_max", "سرینی بزرگ", "Glute max")],
        "biceps": [("long_head", "سر بلند", "Long head")],
        "triceps": [("long_head", "سر بلند", "Long head")],
        "calves": [("gastrocnemius", "دوقلو", "Gastrocnemius")],
        "core": [("abdominals", "شکم", "Abdominals")],
    }
    for muscle_key, rows in regions.items():
        for sort_order, (key, name, name_en) in enumerate(rows):
            MuscleRegion.objects.get_or_create(
                muscle=muscle_rows[muscle_key],
                key=key,
                defaults={"name": name, "name_en": name_en, "sort_order": sort_order},
            )

    equipment = [
        ("bodyweight", "وزن بدن", "Bodyweight"),
        ("dumbbell", "دمبل", "Dumbbell"),
        ("barbell", "هالتر", "Barbell"),
        ("cable", "کابل", "Cable"),
        ("machine", "دستگاه", "Machine"),
        ("smith_machine", "اسمیت", "Smith machine"),
        ("kettlebell", "کتل بل", "Kettlebell"),
        ("resistance_band", "کش", "Resistance band"),
    ]
    equipment_rows = {}
    for sort_order, (key, name, name_en) in enumerate(equipment):
        equipment_rows[key], _ = EquipmentTaxonomy.objects.get_or_create(
            key=key,
            defaults={"name": name, "name_en": name_en, "sort_order": sort_order},
        )

    TrainingTechnique.objects.get_or_create(
        key="superset",
        defaults={
            "name": "سوپرست",
            "description": "اجرای دو حرکت پشت سر هم با استراحت محدود بین آن‌ها.",
            "execution_method": "دو حرکت سازگار را به‌صورت یک جفت اجرا کن و سپس استراحت بده.",
            "parameter_schema": {
                "pairing": {"type": "string", "default": "same_muscle_isolation"},
                "max_pairs": {"type": "integer", "default": 1},
            },
            "handler_key": "superset",
            "sort_order": 10,
        },
    )
    TrainingTechnique.objects.get_or_create(
        key="drop_set",
        defaults={
            "name": "دراپ‌ست",
            "description": "کاهش مرحله‌ای بار یا سختی حرکت بعد از رسیدن به ناتوانی فنی.",
            "execution_method": "پس از ست اصلی، بار را طبق درصد تنظیم‌شده کم کن و ست‌های کاهش‌یافته را اجرا کن.",
            "parameter_schema": {
                "drops": {"type": "integer", "default": 1},
                "reduction_percent": {"type": "integer", "default": 20},
            },
            "handler_key": "drop_set",
            "sort_order": 20,
        },
    )

    # Existing coach-owned rows remain valid. These relations only add structure
    # where the old free-text fields contain information.
    for exercise in Exercise.objects.all().iterator():
        primary_key = _legacy_key("muscle", exercise.primary_muscle)
        primary, _ = MuscleTaxonomy.objects.get_or_create(
            key=primary_key,
            defaults={"name": exercise.primary_muscle, "sort_order": 999},
        )
        ExerciseMuscleTarget.objects.get_or_create(
            exercise=exercise,
            muscle=primary,
            role="primary",
            region=None,
            defaults={"sort_order": 0},
        )
        for index, name in enumerate(exercise.secondary_muscles or [], start=1):
            muscle, _ = MuscleTaxonomy.objects.get_or_create(
                key=_legacy_key("muscle", name),
                defaults={"name": name, "sort_order": 999},
            )
            ExerciseMuscleTarget.objects.get_or_create(
                exercise=exercise,
                muscle=muscle,
                role="secondary",
                region=None,
                defaults={"sort_order": index},
            )
        levels = list(
            Preference.objects.filter(exercise=exercise).values_list("suitable_levels", flat=True)
        )
        level_values = next((value for value in levels if value), None) or [exercise.level]
        if exercise.level == "all":
            level_values = ["beginner", "intermediate", "advanced"]
        for level in level_values:
            if level in {"beginner", "intermediate", "advanced", "all"}:
                ExerciseSuitableLevel.objects.get_or_create(exercise=exercise, level=level)
        if exercise.equipment:
            equipment_key = _legacy_key("equipment", exercise.equipment)
            equipment, _ = EquipmentTaxonomy.objects.get_or_create(
                key=equipment_key,
                defaults={"name": exercise.equipment, "sort_order": 999},
            )
            ExerciseEquipment.objects.get_or_create(exercise=exercise, equipment=equipment)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_assessment_and_style_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="coach_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="coachexercisepreference",
            name="priority",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="EquipmentTaxonomy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("name_en", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="MuscleTaxonomy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("name_en", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="TrainingTechnique",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("execution_method", models.TextField(blank=True, default="")),
                ("parameter_schema", models.JSONField(blank=True, default=dict)),
                ("handler_key", models.CharField(blank=True, default="", max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="MuscleRegion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=120)),
                ("name_en", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "muscle",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="regions", to="accounts.muscletaxonomy"),
                ),
            ],
            options={"ordering": ["muscle", "sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="CoachTechnique",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("execution_method", models.TextField(blank=True, default="")),
                ("allowed_levels", models.JSONField(blank=True, default=list)),
                ("max_per_session", models.PositiveSmallIntegerField(default=0)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_technique",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="coach_overrides", to="accounts.trainingtechnique"),
                ),
                (
                    "coach",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="techniques", to="accounts.coachprofile"),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=("coach", "enabled"), name="coachtech_coach_enabled_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExerciseEquipment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("equipment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="exercise_rows", to="accounts.equipmenttaxonomy")),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="equipment_rows", to="accounts.exercise")),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseMuscleTarget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("primary", "Primary"), ("secondary", "Secondary")], max_length=16)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="muscle_targets", to="accounts.exercise")),
                ("muscle", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="exercise_targets", to="accounts.muscletaxonomy")),
                ("region", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="exercise_targets", to="accounts.muscleregion")),
            ],
            options={
                "ordering": ["role", "sort_order", "muscle__name", "region__name"],
                "indexes": [
                    models.Index(fields=("muscle", "region", "role"), name="ex_target_muscle_region_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExerciseSuitableLevel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("level", models.CharField(choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced"), ("all", "All")], max_length=20)),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="suitable_level_rows", to="accounts.exercise")),
            ],
        ),
        migrations.AddConstraint(
            model_name="muscleregion",
            constraint=models.UniqueConstraint(fields=("muscle", "key"), name="uniq_muscle_region_key"),
        ),
        migrations.AddConstraint(
            model_name="coachtechnique",
            constraint=models.UniqueConstraint(fields=("coach", "key"), name="uniq_coach_technique_key"),
        ),
        migrations.AddConstraint(
            model_name="exerciseequipment",
            constraint=models.UniqueConstraint(fields=("exercise", "equipment"), name="uniq_exercise_equipment"),
        ),
        migrations.AddConstraint(
            model_name="exercisemuscletarget",
            constraint=models.UniqueConstraint(fields=("exercise", "muscle", "region", "role"), name="uniq_exercise_muscle_target"),
        ),
        migrations.AddConstraint(
            model_name="exercisesuitablelevel",
            constraint=models.UniqueConstraint(fields=("exercise", "level"), name="uniq_exercise_suitable_level"),
        ),
        migrations.RunPython(seed_taxonomy_and_migrate_legacy, migrations.RunPython.noop),
    ]
