# Generated by Codex on 2026-09-18

from django.db import migrations


def add_chest_catalog_regions(apps, schema_editor):
    MuscleTaxonomy = apps.get_model("accounts", "MuscleTaxonomy")
    MuscleRegion = apps.get_model("accounts", "MuscleRegion")

    chest = MuscleTaxonomy.objects.get(key="chest")
    regions = (
        ("whole_chest", "کل سینه", "Whole chest", 3),
        ("inner_chest", "داخل سینه", "Inner chest", 4),
        ("inner_upper_chest", "داخل بالاسینه", "Inner upper chest", 5),
        ("inner_lower_chest", "داخل زیرسینه", "Inner lower chest", 6),
    )
    for key, name, name_en, sort_order in regions:
        MuscleRegion.objects.get_or_create(
            muscle=chest,
            key=key,
            defaults={"name": name, "name_en": name_en, "sort_order": sort_order},
        )


class Migration(migrations.Migration):
    dependencies = [("accounts", "0008_exercise_external_key")]

    operations = [migrations.RunPython(add_chest_catalog_regions, migrations.RunPython.noop)]
