# Generated by Django 5.2.17 on 2026-10-08 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_chest_catalog_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementCatalogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(max_length=120)),
                ('reason', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('replacement_group', models.CharField(blank=True, max_length=120)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('auto_eligible', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['-priority', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplementDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('unit', models.CharField(choices=[('scoop', 'اسکوپ'), ('gram', 'گرم'), ('mg', 'میلی\u200cگرم'), ('serving', 'سروینگ'), ('tablet', 'قرص'), ('capsule', 'کپسول'), ('ml', 'میلی\u200cلیتر'), ('piece', 'عدد')], max_length=20)),
                ('timing', models.CharField(choices=[('morning', 'صبح'), ('with_meal', 'همراه غذا'), ('before_workout', 'قبل تمرین'), ('after_workout', 'بعد تمرین'), ('bedtime', 'قبل خواب'), ('custom', 'زمان دلخواه')], max_length=30)),
                ('custom_time', models.CharField(blank=True, max_length=120)),
                ('days', models.CharField(choices=[('all', 'همه روزها'), ('training', 'روز تمرین'), ('rest', 'روز استراحت')], default='all', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='accounts.supplementcatalogentry')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplementGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coachprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='supplementcatalogentry',
            name='goals',
            field=models.ManyToManyField(blank=True, to='accounts.supplementgoal'),
        ),
        migrations.AddConstraint(
            model_name='supplementgoal',
            constraint=models.UniqueConstraint(fields=('coach', 'name'), name='supp_goal_coach_name'),
        ),
        migrations.AddConstraint(
            model_name='supplementcatalogentry',
            constraint=models.UniqueConstraint(fields=('coach', 'name'), name='supp_entry_coach_name'),
        ),
    ]
