# Generated by Django 5.2.17 on 2026-10-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_supplementcatalogentry_supplementdose_supplementgoal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='calendar',
            field=models.CharField(choices=[('persian', 'Persian'), ('gregory', 'Gregorian')], default='persian', max_length=12),
        ),
    ]
